# cPanel deployment configuration for a Next.js application.
# This file assumes that the Node.js application is run directly
# from the repository's root directory in the cPanel environment.
---
deployment:
  tasks:
    # The Node.js environment in cPanel uses a global directory for modules, which can get corrupted.
    # The following command forcefully removes this specific directory to ensure a clean slate.
    # The path is derived from the npm error log.
    - /bin/rm -rf /home/desainrs/nodevenv/repositories/studio/22/lib/node_modules

    # We also remove the local node_modules and package-lock.json for good measure.
    - /bin/rm -rf node_modules package-lock.json

    # Clean the npm cache.
    - /bin/npm cache clean --force

    # Re-run the installation, logging the output.
    - /bin/npm install --production=false > npm_install.log 2>&1

    # Build the Next.js application for production.
    - /bin/npm run build

    # Restart the Phusion Passenger server.
    - /bin/mkdir -p tmp
    - /bin/touch tmp/restart.txt 