---
deployment:
  tasks:
    # On every deployment, we forcefully remove everything that our smart launcher
    # script will regenerate. The path has been updated to the new application directory.
    - /bin/rm -rf /home/desainrs/nodevenv/repositories/DesAInR/20/lib/node_modules node_modules .next npm_install.log package-lock.json 