# cPanel deployment configuration for a Next.js application.
# This file assumes that the Node.js application is run directly
# from the repository's root directory in the cPanel environment.
---
deployment:
  tasks:
    # Install npm dependencies and redirect all output (stdout and stderr) to a log file.
    # This captures the detailed error message when the cPanel UI hides it.
    - /bin/npm install --production=false > npm_install.log 2>&1

    # Build the Next.js application for production.
    - /bin/npm run build

    # Restart the Phusion Passenger server (if used by the cPanel Node.js setup).
    # This is done by creating/touching the restart.txt file in the tmp directory.
    - /bin/mkdir -p tmp
    - /bin/touch tmp/restart.txt 