# cPanel deployment configuration for a Next.js application.
# This file assumes that the Node.js application is run directly
# from the repository's root directory in the cPanel environment.
---
deployment:
  tasks:
    # Forcefully clean the npm cache to resolve potential corruption.
    - /bin/npm cache clean --force

    # Remove the existing node_modules and package-lock.json to ensure a completely clean install.
    - /bin/rm -rf node_modules package-lock.json

    # Install npm dependencies and log the output for debugging.
    - /bin/npm install --production=false > npm_install.log 2>&1

    # Build the Next.js application for production.
    - /bin/npm run build

    # Restart the Phusion Passenger server.
    - /bin/mkdir -p tmp
    - /bin/touch tmp/restart.txt 