---
deployment:
  tasks:
    # On every deployment, we forcefully remove everything that our smart launcher
    # script will regenerate. This ensures a completely fresh start. This includes
    # the global and local node_modules, the .next build folder, old logs, and lock files.
    - /bin/rm -rf /home/desainrs/nodevenv/repositories/studio/20/lib/node_modules node_modules .next npm_install.log package-lock.json 