---
deployment:
  tasks:
    # On every deployment, we will forcefully remove the node_modules directories
    # and the old log file. This ensures our new app.js launcher script always
    # starts from a clean state and performs a fresh installation if needed.
    - /bin/rm -rf /home/desainrs/nodevenv/repositories/studio/20/lib/node_modules node_modules npm_install.log 